
name: Generate Project Tree

on:
  workflow_dispatch: # Avvio manuale
  push:
    branches:
      - main

jobs:
  generate-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tree utility
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate project tree
        run: |
          tree -I 'node_modules|.git' > project_tree.txt
          cat project_tree.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-tree
